name: jd-sign bot

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 1 * * *'
jobs:
    deploy:
        runs-on: ubuntu-18.04

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: install
              run: npm install
            - name: build
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
              run: |
                node app.js
